import { ThemeDefinition, ThemeId } from "./types";

export const DEFAULT_THEME_ID: ThemeId = "catppuccin-mocha";

export const THEMES: readonly ThemeDefinition[] = [
    {
        id: "catppuccin-mocha",
        label: "Catppuccin",
        variantLabel: "Mocha",
        className: "nc-theme-catppuccin-mocha",
        colorScheme: "dark",
        accent: "#658ff2",
        surface: "#1e1e2e",
        ink: "#c6d0f5",
        uiFont: '"Inter Variable", Inter, "Segoe UI Variable Text", "Segoe UI", system-ui, sans-serif',
        codeFont: '"JetBrains Mono Variable", "JetBrains Mono", "Cascadia Code", Consolas, monospace',
        opaqueWindows: false,
        contrast: 60,
        semanticColors: {
            diffAdded: "#a6e3a1",
            diffRemoved: "#f38ba8",
            skill: "#cba6f7",
        },
    },
    {
        id: "tokyo-night",
        label: "Tokyo Night",
        variantLabel: "Dark",
        className: "nc-theme-tokyo-night",
        colorScheme: "dark",
        accent: "#3d59a1",
        surface: "#1a1b26",
        ink: "#a9b1d6",
        uiFont: '"Inter Variable", Inter, "Segoe UI Variable Text", "Segoe UI", system-ui, sans-serif',
        codeFont: '"JetBrains Mono Variable", "JetBrains Mono", "Cascadia Code", Consolas, monospace',
        opaqueWindows: false,
        contrast: 60,
        semanticColors: {
            diffAdded: "#449dab",
            diffRemoved: "#914c54",
            skill: "#9d7cd8",
        },
    },
    {
        id: "absolutely",
        label: "Absolutely",
        variantLabel: "Dark",
        className: "nc-theme-absolutely",
        colorScheme: "dark",
        accent: "#cc7d5e",
        surface: "#2d2d2b",
        ink: "#f9f9f7",
        uiFont: '"Inter Variable", Inter, "Segoe UI Variable Text", "Segoe UI", system-ui, sans-serif',
        codeFont: '"JetBrains Mono Variable", "JetBrains Mono", "Cascadia Code", Consolas, monospace',
        opaqueWindows: true,
        contrast: 60,
        semanticColors: {
            diffAdded: "#00c853",
            diffRemoved: "#ff5f38",
            skill: "#cc7d5e",
        },
    },
    {
        id: "ayu",
        label: "Ayu",
        variantLabel: "Dark",
        className: "nc-theme-ayu",
        colorScheme: "dark",
        accent: "#e6b450",
        surface: "#10141c",
        ink: "#bfbdb6",
        uiFont: '"Inter Variable", Inter, "Segoe UI Variable Text", "Segoe UI", system-ui, sans-serif',
        codeFont: '"JetBrains Mono Variable", "JetBrains Mono", "Cascadia Code", Consolas, monospace',
        opaqueWindows: true,
        contrast: 60,
        semanticColors: {
            diffAdded: "#70bf56",
            diffRemoved: "#f26d78",
            skill: "#d0a1ff",
        },
    },
    {
        id: "github",
        label: "GitHub",
        variantLabel: "Dark",
        className: "nc-theme-github",
        colorScheme: "dark",
        accent: "#1f6feb",
        surface: "#0d1117",
        ink: "#e6edf3",
        uiFont: '"Inter Variable", Inter, "Segoe UI Variable Text", "Segoe UI", system-ui, sans-serif',
        codeFont: '"JetBrains Mono Variable", "JetBrains Mono", "Cascadia Code", Consolas, monospace',
        opaqueWindows: true,
        contrast: 60,
        semanticColors: {
            diffAdded: "#3fb950",
            diffRemoved: "#f85149",
            skill: "#bc8cff",
        },
    },
    {
        id: "linear",
        label: "Linear",
        variantLabel: "Dark",
        className: "nc-theme-linear",
        colorScheme: "dark",
        accent: "#606acc",
        surface: "#0f0f11",
        ink: "#e3e4e6",
        uiFont: '"Inter Variable", Inter, "Segoe UI Variable Text", "Segoe UI", system-ui, sans-serif',
        codeFont: '"JetBrains Mono Variable", "JetBrains Mono", "Cascadia Code", Consolas, monospace',
        opaqueWindows: true,
        contrast: 60,
        semanticColors: {
            diffAdded: "#69c967",
            diffRemoved: "#ff7e78",
            skill: "#c2a1ff",
        },
    },
    {
        id: "lobster",
        label: "Lobster",
        variantLabel: "Dark",
        className: "nc-theme-lobster",
        colorScheme: "dark",
        accent: "#ff5c5c",
        surface: "#111827",
        ink: "#e4e4e7",
        uiFont: 'Satoshi, "Inter Variable", Inter, "Segoe UI Variable Text", "Segoe UI", system-ui, sans-serif',
        codeFont: '"JetBrains Mono Variable", "JetBrains Mono", "Cascadia Code", Consolas, monospace',
        opaqueWindows: true,
        contrast: 60,
        semanticColors: {
            diffAdded: "#22c55e",
            diffRemoved: "#ff5c5c",
            skill: "#3b82f6",
        },
    },
    {
        id: "matrix",
        label: "Matrix",
        variantLabel: "Dark",
        className: "nc-theme-matrix",
        colorScheme: "dark",
        accent: "#1eff5a",
        surface: "#040805",
        ink: "#b8ffca",
        uiFont: '"JetBrains Mono Variable", "JetBrains Mono", "Cascadia Code", Consolas, monospace',
        codeFont: '"JetBrains Mono Variable", "JetBrains Mono", "Cascadia Code", Consolas, monospace',
        opaqueWindows: true,
        contrast: 60,
        semanticColors: {
            diffAdded: "#1eff5a",
            diffRemoved: "#fa423e",
            skill: "#1eff5a",
        },
    },
    {
        id: "one",
        label: "One",
        variantLabel: "Dark",
        className: "nc-theme-one",
        colorScheme: "dark",
        accent: "#4d78cc",
        surface: "#282c34",
        ink: "#abb2bf",
        uiFont: '"Inter Variable", Inter, "Segoe UI Variable Text", "Segoe UI", system-ui, sans-serif',
        codeFont: '"JetBrains Mono Variable", "JetBrains Mono", "Cascadia Code", Consolas, monospace',
        opaqueWindows: true,
        contrast: 60,
        semanticColors: {
            diffAdded: "#8cc265",
            diffRemoved: "#e05561",
            skill: "#c162de",
        },
    },
    {
        id: "oscurange",
        label: "Oscurange",
        variantLabel: "Dark",
        className: "nc-theme-oscurange",
        colorScheme: "dark",
        accent: "#f9b98c",
        surface: "#0b0b0f",
        ink: "#e6e6e6",
        uiFont: '"Inter Variable", Inter, "Segoe UI Variable Text", "Segoe UI", system-ui, sans-serif',
        codeFont: '"JetBrains Mono Variable", "JetBrains Mono", "Cascadia Code", Consolas, monospace',
        opaqueWindows: true,
        contrast: 60,
        semanticColors: {
            diffAdded: "#40c977",
            diffRemoved: "#fa423e",
            skill: "#479ffa",
        },
    },
    {
        id: "raycast",
        label: "Raycast",
        variantLabel: "Dark",
        className: "nc-theme-raycast",
        colorScheme: "dark",
        accent: "#ff6363",
        surface: "#101010",
        ink: "#fefefe",
        uiFont: '"Inter Variable", Inter, "Segoe UI Variable Text", "Segoe UI", system-ui, sans-serif',
        codeFont: '"JetBrains Mono Variable", "JetBrains Mono", "Cascadia Code", Consolas, monospace',
        opaqueWindows: false,
        contrast: 60,
        semanticColors: {
            diffAdded: "#59d499",
            diffRemoved: "#ff6363",
            skill: "#cf2f98",
        },
    },
    {
        id: "rose-pine",
        label: "Rose Pine",
        variantLabel: "Moon",
        className: "nc-theme-rose-pine",
        colorScheme: "dark",
        accent: "#ea9a97",
        surface: "#232136",
        ink: "#e0def4",
        uiFont: '"Inter Variable", Inter, "Segoe UI Variable Text", "Segoe UI", system-ui, sans-serif',
        codeFont: '"JetBrains Mono Variable", "JetBrains Mono", "Cascadia Code", Consolas, monospace',
        opaqueWindows: false,
        contrast: 60,
        semanticColors: {
            diffAdded: "#9ccfd8",
            diffRemoved: "#908caa",
            skill: "#c4a7e7",
        },
    },
    {
        id: "vercel",
        label: "Vercel",
        variantLabel: "Dark",
        className: "nc-theme-vercel",
        colorScheme: "dark",
        accent: "#006efe",
        surface: "#000000",
        ink: "#ededed",
        uiFont: '"Geist Variable", Geist, "Inter Variable", Inter, "Segoe UI", system-ui, sans-serif',
        codeFont: '"Geist Mono Variable", "Geist Mono", "JetBrains Mono Variable", "Cascadia Code", Consolas, monospace',
        opaqueWindows: true,
        contrast: 50,
        semanticColors: {
            diffAdded: "#00AD3A",
            diffRemoved: "#F13342",
            skill: "#9540D5",
        },
    },
    {
        id: "vscode-plus",
        label: "VS Code Plus",
        variantLabel: "Dark",
        className: "nc-theme-vscode-plus",
        colorScheme: "dark",
        accent: "#007acc",
        surface: "#1e1e1e",
        ink: "#d4d4d4",
        uiFont: '"Geist Variable", Geist, "Inter Variable", Inter, "Segoe UI", system-ui, sans-serif',
        codeFont: '"Geist Mono Variable", "Geist Mono", "JetBrains Mono Variable", "Cascadia Code", Consolas, monospace',
        opaqueWindows: true,
        contrast: 50,
        semanticColors: {
            diffAdded: "#369432",
            diffRemoved: "#f44747",
            skill: "#000080",
        },
    },
];

export function getTheme(id: string | null | undefined): ThemeDefinition {
    return THEMES.find((theme) => theme.id === id) ?? THEMES[0];
}
